src/SolSSIApp/src/mx/com/metlife/solssi/catalogo/domain/CatalogoItem.java
package mx.com.metlife.solssi.catalogo.domain;
import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.apache.commons.lang.StringUtils;

@Entity
@Table(name="TC_DETALLE_CATALOGO")
public class CatalogoItem implements Serializable {
	
	private static final long serialVersionUID = 1L;
	
	@EmbeddedId	
	private CatalogoPK clave;
	
	@Column(name="CVE_ESTATUS")
	private Boolean estatus;

	@Column(name="VALOR_CAMPO1")
	private String descripcion;

	@Column(name="VALOR_CAMPO2")
	private String valorCampo2;
	
	@Column(name="VALOR_CAMPO3")
	private String valorCampo3;
	
	@Column(name="VALOR_CAMPO4")
	private String valorCampo4;
	
	@Column(name="VALOR_CAMPO5")
	private String valorCampo5;
	
	@Column(name="VALOR_CAMPO6")
	private String valorCampo6;
	
	@Column(name="VALOR_CAMPO7")
	private String valorCampo7;
	
	@Transient
	private String descDependencia;

	public CatalogoItem() {
		super();
	}

	
	public Integer getIdCatalogo(){
		return this.clave.getId();
	}
	
	public String getClaveItem(){
		return this.clave.getClave();
	}
	
	public CatalogoPK getClave() {
		return this.clave;
	}

	public void setClave(CatalogoPK clave) {
		this.clave = clave;
	}

	/**
	 * @return el estatus
	 */
	public Boolean getEstatus() {
		return estatus;
	}

	/**
	 * @param estatus el estatus a establecer
	 */
	public void setEstatus(Boolean estatus) {
		this.estatus = estatus;
	}

	/**
	 * @return el descripcion
	 */
	public String getDescripcion() {
		return StringUtils.upperCase(StringUtils.trim(descripcion));
	}
	
	public String getDescripcionOrigen() {
		return StringUtils.trim(descripcion);
	}

	/**
	 * @param descripcion el descripcion a establecer
	 */
	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	/**
	 * @return el valorCampo2
	 */
	public String getValorCampo2() {
		return StringUtils.upperCase(StringUtils.trim(valorCampo2));
	}

	/**
	 * @param valorCampo2 el valorCampo2 a establecer
	 */
	public void setValorCampo2(String valorCampo2) {
		this.valorCampo2 = valorCampo2;
	}


	/**
	 * @return the valorCampo3
	 */
	public String getValorCampo3() {
		return StringUtils.trim(valorCampo3);
	}


	/**
	 * @param valorCampo3 the valorCampo3 to set
	 */
	public void setValorCampo3(String valorCampo3) {
		this.valorCampo3 = valorCampo3;
	}


	public String getValorCampo4() {
		return valorCampo4;
	}


	public void setValorCampo4(String valorCampo4) {
		this.valorCampo4 = valorCampo4;
	}


	public String getValorCampo5() {
		return valorCampo5;
	}


	public void setValorCampo5(String valorCampo5) {
		this.valorCampo5 = valorCampo5;
	}
	
	

	/**
	 * @return the valorCampo6
	 */
	public String getValorCampo6() {
		return valorCampo6;
	}


	/**
	 * @param valorCampo6 the valorCampo6 to set
	 */
	public void setValorCampo6(String valorCampo6) {
		this.valorCampo6 = valorCampo6;
	}


	/**
	 * @return the valorCampo7
	 */
	public String getValorCampo7() {
		return valorCampo7;
	}


	/**
	 * @param valorCampo7 the valorCampo7 to set
	 */
	public void setValorCampo7(String valorCampo7) {
		this.valorCampo7 = valorCampo7;
	}


	public String getDescDependencia(){
		if(this.descDependencia == null){
			StringBuffer buf = new StringBuffer();
			buf.append("( ").append(StringUtils.trim(valorCampo3)).append(" - ").append(StringUtils.trim(valorCampo4)).append(" )  ");
			buf.append(StringUtils.trim(descripcion));
			this.descDependencia =  buf.toString();
		}
		return descDependencia;
	}


}

src/SolSSIApp/src/mx/com/metlife/solssi/autorizacion/mvc/AutorizacionController.java
package mx.com.metlife.solssi.autorizacion.mvc;

import java.util.List;

import javax.servlet.http.HttpSession;
import javax.validation.Valid;

import mx.com.metlife.solssi.consulta.domain.ConsultaFilter;
import mx.com.metlife.solssi.exception.ApplicationException;
import mx.com.metlife.solssi.inicio.service.GruposCapturaService;
import mx.com.metlife.solssi.solicitud.domain.Solicitud;
import mx.com.metlife.solssi.solicitud.service.SolicitudService;
import mx.com.metlife.solssi.usuario.domain.UserPrincipal;
import mx.com.metlife.solssi.usuario.domain.Usuario;
import mx.com.metlife.solssi.util.AppConstants;
import mx.com.metlife.solssi.util.BrowserUtils;
import mx.com.metlife.solssi.util.message.MessageUtils;

import org.apache.commons.lang.StringUtils;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.security.core.Authentication;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;

@Controller
@RequestMapping("autorizacion")
public class AutorizacionController {
	
	@Autowired
	private SolicitudService solicitudService;
	
	@Autowired
	private GruposCapturaService groupService;
	
	@RequestMapping(method=RequestMethod.POST)
	public String showConsulta(Model model, HttpSession session){
		
		session.removeAttribute("solicitud");
		
		model.addAttribute(new ConsultaFilter());
		return "autorizacion";
	}
	
	
	@RequestMapping(value = "consulta", method=RequestMethod.POST)
	public String executeConsulta(@Valid ConsultaFilter filtro, BindingResult errors, Model model, Authentication auth){
		
		Usuario usuario = ((UserPrincipal)auth.getPrincipal()).getUsuario();
		
		model.addAttribute(filtro);
		
		if(usuario.getDependencia() == null || usuario.getDependencia() <= 0){
			errors.reject("NotEmpty.consultaFilter.dependencia");
		}
		
		if(filtro.isEmpty()){
			errors.reject("NotEmpty.consultaFilter.object");
			return "autorizacion";
		}
		
		if(errors.hasErrors()){
			return "autorizacion";	
		}
		
		filtro.setDependencia(usuario.getDependencia());
		filtro.setEstatus(AppConstants.ESTATUS_CAPTURA);
		List<Solicitud> list = solicitudService.get(filtro);
		
		if(list == null || list.isEmpty()){
			if(filtro.getNumFolio()!=null && filtro.getNumFolio()>0){
				errors.reject("NotEmpty.auth.result.folio");	
			}else{
				errors.reject("NotEmpty.auth.result.rfc_cuenta");
			}
		}
		
		model.addAttribute("solicitudes", list);
		
		BrowserUtils.enableHistoryBack(model);
		
		return "autorizacion";
	}
	
	@RequestMapping(value = "desplegar", method=RequestMethod.POST)
	public String showSolicitud(@RequestParam("numFolio") Integer folio, HttpSession session, Model model){
		
		Solicitud solicitud = solicitudService.get(folio);
		session.setAttribute("solicitud", solicitud);
		model.addAttribute("auth", true);
		
		return "autorizacion/solicitud";
	}
	
	
	
	@RequestMapping(value = "execute/autorizacion", method=RequestMethod.POST)
	public String executeAutorizacion(@RequestParam(value = "checkClabe", required = false) String checkClabe, Model model, HttpSession session, Authentication auth){
		
		Usuario usuario = ((UserPrincipal)auth.getPrincipal()).getUsuario();
		
		Solicitud solicitud = (Solicitud) session.getAttribute("solicitud");
		
		try {
			
			groupService.checkMaxFechaAutorization();
			
			if(StringUtils.isNotEmpty(checkClabe)){
				String clabe = solicitudService.getClabe(solicitud.getNumFolio());
				if(!StringUtils.equals(clabe, checkClabe)){
					throw new ApplicationException(MessageUtils.getMessage("check.clabe.NotMatch"));
				}
			}
			
			groupService.checkFechaMaxAutorizacion(solicitud.getRfc(), solicitud.getCuenta());
			
			solicitudService.updateEstatusAutorizacion(solicitud, AppConstants.ESTATUS_ACEPTADO, usuario.getClave());
			model.addAttribute("autorizado", "true");
		} catch (ApplicationException e) {
			model.addAttribute("error", e.getMessage());
		}
		
		model.addAttribute("folio", solicitud.getUserFolio());
		
		session.removeAttribute("solicitud");
		
		return "autorizacion/result";
	}
	
	
	
	
	@RequestMapping(value = "execute/rechazo" , method=RequestMethod.POST)
	public String executeRechazo(Model model, HttpSession session, Authentication auth){
		try {
			
			groupService.checkMaxFechaAutorization();
			
			Usuario usuario = ((UserPrincipal)auth.getPrincipal()).getUsuario();
			
			Solicitud solicitud = (Solicitud) session.getAttribute("solicitud");
			model.addAttribute("folio", solicitud.getUserFolio());
			
			groupService.checkFechaMaxAutorizacion(solicitud.getRfc(), solicitud.getCuenta());
			solicitudService.updateEstatusAutorizacion(solicitud, AppConstants.ESTATUS_RECHAZADO, usuario.getClave());
			model.addAttribute("rechazado", "true");
			
		} catch (ApplicationException e) {
			model.addAttribute("error", e.getMessage());
		}
		
		session.removeAttribute("solicitud");
		
		return "autorizacion/result";
	}


}

src/SolSSIApp/WebContent/WEB-INF/jsp/autorizacion/autoriza_solicitud.jsp
<%@ page contentType="text/html" isELIgnored="false"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt"%>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form"%>
<%@ taglib prefix="s" uri="http://www.springframework.org/tags"%>



<s:url value="/autorizacion" var="urlConsulta"/>
<s:url value="/autorizacion/execute/autorizacion" var="urlAutoriza"/>
<s:url value="/autorizacion/execute/rechazo" var="urlRechazo"/>

<style>
	.buttonDlg{
		background-color: #f5f5f5;
		color: black;
		border: 1px solid gray;
	}
</style>
		
<script>
		 
		var checkListDialog;
		var confirmDialog;
		var confirmRechazoDialog;
		var clabeDialog;
		var checkItem;
		dojo.require("dijit.Dialog");
		
		dojo.ready(function(){
			  
			checkListDialog = new dijit.Dialog({ title:"<s:message code='dialog.checklist.title' htmlEscape='true'/>", style: "width: 875px;text-align:center" }, "divCheckList");
			dojo.style(dijit.byId("divCheckList").closeButtonNode,"display","none");
  			checkListDialog.startup();
  			
  			
  			confirmDialog = new dijit.Dialog({ title:"", style: "width: 700px;text-align:center" }, "divConfirm");
  			dojo.style(dijit.byId("divConfirm").closeButtonNode,"display","none");
  			confirmDialog.startup();
  			
  			clabeDialog = new dijit.Dialog({ title:"Capture la CLABE", style: "width: 500px;text-align:center" }, "divCapturaClabe");
  			dojo.style(dijit.byId("divCapturaClabe").closeButtonNode,"display","none");
  			clabeDialog.startup();
  			
  			confirmRechazoDialog = new dijit.Dialog({ title:"Mensaje", style: "width: 500px;text-align:center" }, "divRechazar");
  			dojo.style(dijit.byId("divRechazar").closeButtonNode,"display","none");
  			confirmRechazoDialog.startup();
  			
			
			<c:if test="${solicitud.contribuyenteEUA}">
	 			js_solicitud.showNSS(true);
	 	    </c:if>
	 	   
	 		<c:if test="${solicitud.idPaisNac gt 0}">
	 			checkPaisNacimiento(<c:out value="${solicitud.idPaisNac}"/>);
	 		</c:if>
	 		
	 		<c:if test="${solicitud.idPais gt 0}">
	 			checkPaisDomicilio(<c:out value="${solicitud.idPais}"/>);
			</c:if>
		});
		
		function showConfirmDialog(){
			confirmDialog.show();
		}
		
		function confirmRechazar(){
			document.forms["solicitud"].action = "${urlRechazo}";
			document.forms["solicitud"].target = "_top";
			submitForm(document.forms["solicitud"]);
		}
		
		function cancelRechazar(){
			confirmDialog.hide();
		}
		 
		 function dependientes() {
			 openWindowCenterScroll("","dep",1000,600);
			 document.forms["dependientes"].submit();
		 };
		 
		 
		 function checkPaisNacimiento(value){
			 if(value == 1){
				 document.getElementById("divEstadoNacExtranjero").style.display = "none";
				 document.getElementById("divEstadoNacMexico").style.display = "";
			 }else{
				 document.getElementById("divEstadoNacMexico").style.display = "none";
				 document.getElementById("divEstadoNacExtranjero").style.display = "";
			 }
		 }
		 
		 
		 function checkPaisDomicilio(value){
			 if(value == 1){
				 document.getElementById("divEstadoExtranjero").style.display = "none";
				 document.getElementById("divEstadoMexico").style.display = "";
				 document.getElementById("divMunicipioExtranjero").style.display = "none";
				 document.getElementById("divMunicipioMexico").style.display = "";
			 }else{
				 document.getElementById("divEstadoMexico").style.display = "none";
				 document.getElementById("divEstadoExtranjero").style.display = "";
				 document.getElementById("divMunicipioMexico").style.display = "none";
				 document.getElementById("divMunicipioExtranjero").style.display = "";
			 }
		 }
		 
		 function regresarConsulta(){
			 history.back();
		 }
		 
		 function checkListDialogOpen(){
	  	 	 for(var i = 0; i < document.forms["checkListForm"].clItem.length; i++){
		 	 	document.forms["checkListForm"].clItem[i].checked = false;
		 	 }
		 	 try{
		 	 		dojo.byId("checkListClabeError").style.display = 'none';
		 	 	}catch(e){
		 	 };
		 	 checkListDialog.show();
		 }
		 
		 function checkListDialogClose(){
		 	 checkListDialog.hide();
		 }
		 
		 function autorizar(){
		 	 
		 	 for(var i = 0; i < document.forms["checkListForm"].clItem.length; i++){
		 	 	if(!document.forms["checkListForm"].clItem[i].checked){
		 	 		showConfirmDialog();
		 	 		return;		
		 	 	}
		 	 }
			 
			 document.forms["solicitud"].action = "${urlAutoriza}";
			 document.forms["solicitud"].target = "_top";
			 submitForm(document.forms["solicitud"]);
		 }

		 function capturarClabe(){
		 	clabeDialog.show();
		 }
		 
		 function cerrarDlgClabe(){
		 	clabeDialog.hide();
		 }
		 
		 function validaCLABE_KEYUP(){
		    if(dojo.byId("inputCheckClabe").value.length == 18){
			 	if(dojo.byId("inputCheckClabe").value != '<c:out value="${solicitud.clabe}"/>'){
			 		dojo.byId("checkListClabeError").style.display = '';
			 	}else{
			 		dojo.byId("checkListClabeError").style.display = 'none';
			 	}
		 	}
		 }
		 
		 function validaCLABE(){
			 	if(dojo.byId("inputCheckClabe").value != '<c:out value="${solicitud.clabe}"/>'){
			 		dojo.byId("checkListClabeError").style.display = '';
			 		return false;
			 	}else{
			 		dojo.byId("checkListClabeError").style.display = 'none';
			 	}
			 	return true;
		 }
		 
		 function checkCLABE(check){
		 	if(check.checked){
		 		if(!validaCLABE()){
		 			check.checked = false;
		 		}
		 	}else{
		 		dojo.byId("checkListClabeError").style.display = 'none';
		 		document.forms["solicitud"].checkClabe.value = dojo.byId("inputCheckClabe").value;
		 	}
		 }
		 
</script>

<div class="moduleTitle"><span><s:message code="module.title.solicitud.autorizacion" htmlEscape="true"/></span></div>

<jsp:include page="../consulta/datos_solicitud.jsp"/>	

<br/><br/>
<div>
	<button type="button" class="btnEnviar" onclick="regresarConsulta()"><span><em><s:message code="button.cancelar" htmlEscape="true"/></em></span></button>
	<c:if test="${solicitud.cveStatus == 1}">
		<button type="button" class="btnEnviar" onclick="checkListDialogOpen()"><span><em><s:message code="button.autorizar" htmlEscape="true"/></em></span></button>
	</c:if>
</div>
<br/><br/>		

<form name="dependientes" action="<s:url value='/consulta/dependientes/'/>" target="dep" method="post"/>
	<input type="hidden" name="folio" value="<c:out value='${solicitud.numFolio}'/>">
</form>

<jsp:include page="checklist.jsp"/>

src/SolSSIApp/WebContent/WEB-INF/jsp/autorizacion/checklist.jsp
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt"%>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form"%>
<%@ taglib prefix="s" uri="http://www.springframework.org/tags"%>

<div id="divCheckList" style="min-height: 500px;">
	<div align="center" style="width:100%">
		<div align="left" style="width: 100%">
			<form name="checkListForm">
				<table cellspacing="7" cellpadding="7">
					
					<tr>
						<td colspan="2"></td>
					</tr>
					
					<c:if test="${solicitud.prestamo}">
						<tr>
							<td colspan="2" align="justify">
								<div class="ui-state-active ui-corner-all" style="padding: 5px 5px 5px 5px">
									<div align="center"><span style="color:blue"><strong>Recordatorio:</strong></span></div>
									<span style="color:black">
										<s:message code="auth.prestamo.recordatorio" htmlEscape="true"/>
									</span>
								</div>
							</td>
						</tr>
					</c:if>
					
					<tr>
						<c:set var="st" value="1"/>
						<td align="left">
							<input type="checkbox" name="clItem" id="clItem${st}">
						</td>
						<td align="left">
							<label for="clItem${st}"><c:out value="${CATALOGO.CHECKLIST['1'].descripcionOrigen}"/></label>
						</td>
					</tr>
					<tr>
						<c:set var="st" value="${st+1}"/>
						<td align="left">
							<input type="checkbox" name="clItem" id="clItem${st}">
						</td>
						<td align="left">
							<label for="clItem${st}"><c:out value="${CATALOGO.CHECKLIST['2'].descripcionOrigen}"/></label>
						</td>
					</tr>
					
					<c:if test="${(solicitud.bndUltimosDigitosClabe) and (solicitud.modoPago eq 1)}">
						<tr>
							<c:set var="st" value="${st+1}"/>
							<td align="left">
								<input type="checkbox" name="clItem" id="clItem${st}">
							</td>
							<td align="left">
								<label for="clItem${st}"><c:out value="${CATALOGO.CHECKLIST['3'].descripcionOrigen}"/></label>
							</td>
						</tr>
						<tr>
							<c:set var="st" value="${st+1}"/>
							<td align="left">
								<input type="checkbox" name="clItem" id="clItem${st}">
							</td>
							<td align="left">
								<label for="clItem${st}"><c:out value="${CATALOGO.CHECKLIST['4'].descripcionOrigen}"/></label>
							</td>
						</tr>
							
					</c:if>
					<c:if test="${(not solicitud.bndUltimosDigitosClabe) and (solicitud.modoPago eq 1)}">
						<tr>
							<c:set var="st" value="${st+1}"/>
							<td align="left">
								<input type="checkbox" name="clItem" id="clItem${st}">
							</td>
							<td align="left">
								<label for="clItem${st}"><c:out value="${CATALOGO.CHECKLIST['7'].descripcionOrigen}"/></label>
							</td>
						</tr>
						<tr>
							<c:set var="st" value="${st+1}"/>
							<td align="left">
								<input type="checkbox" name="clItem" id="clItem${st}" onclick="checkCLABE(this)">
							</td>
							<td align="left">
								<label for="clItem${st}"><c:out value="${CATALOGO.CHECKLIST['8'].descripcion}"/></label>
								<input id="inputCheckClabe" type="text" onkeypress="return enableNumero(event);" maxlength="18" size="18" onpaste="return false" onkeyup="validaCLABE_KEYUP()">
								<span class="error" id="checkListClabeError" style="display: none"><s:message code="check.clabe.NotMatch" htmlEscape="true"/></span>
							</td>
						</tr>
							
					</c:if>
					
					<tr>
							<c:set var="st" value="${st+1}"/>
							<td align="left">
								<input type="checkbox" name="clItem" id="clItem${st}">
							</td>
							<td align="left">
								<label for="clItem${st}"><c:out value="${CATALOGO.CHECKLIST['5'].descripcionOrigen}"/></label>
							</td>
					</tr>
					<tr>
							<c:set var="st" value="${st+1}"/>
							<td align="left">
								<input type="checkbox" name="clItem" id="clItem${st}">
							</td>
							<td align="left">
								<label for="clItem${st}"><c:out value="${CATALOGO.CHECKLIST['6'].descripcionOrigen}"/></label>
							</td>
					</tr>
					
				</table>
			</form>	
			<div align="center">	
				<button type="button" class="btnEnviar" onclick="checkListDialogClose()"><span><em>Cancelar</em></span></button>
				<button type="button" class="btnEnviar" onclick="autorizar()"><span><em>Enviar</em></span></button>
			</div>
		</div>
	</div>
</div>

<div id="divConfirm">
	<div align="center" style="width:100%">
	    <table>
	    	<tr>
	    		<td valign="top">
	    			<img src="<s:url value='/resources/images/info.gif'/>"/>
	    		</td>
	    		<td>
	    			<span id="textConfirm" style="color:black;font-size:14px">
						<s:message code="documentacion.auth.incompleta" htmlEscape="true"/>
					</span>
	    		</td>
	    		
	    	</tr>
	    </table>
		
		<div>
			<br/>
			<input type="button" value="Cancelar" onclick="cancelRechazar()" class="buttonDlg" style="width: 60px"/>
			<input type="button" value="Aceptar" onclick="confirmRechazar()" class="buttonDlg" style="width: 60px"/>
			
		</div>
	</div>
</div>


<div id="divRechazar">
	<div align="center" style="width:100%">
		<div style="position: absolute;top: 5px;left: 15px">
			<img src="<s:url value='/resources/images/info.gif'/>"/>
		</div>
		<div>
			<span id="textConfirm" style="color:black;font-size:14px">
				<s:message code="confirm.rechazo.solicitud" htmlEscape="true"/>
			</span>
		</div>
		<div>
			<br/>
			<input type="button" value="No" onclick="cancelRechazar()" class="buttonDlg" style="width: 60px"/>
			<input type="button" value="Si" onclick="confirmRechazar()" class="buttonDlg" style="width: 60px"/>
		</div>
	</div>
</div>


<div id="divCapturaClabe">
	<div align="center" style="width:100%">
		<div align="center">
			<label>Clabe:</label><input name="clabe" type="text" maxlength="18" width="150px" id="inputCheckClabe"/>
		</div>
		<div style="min-height: 30px" >
			<span class="error" id="checkListClabeError" style="display: none"><s:message code="check.clabe.NotMatch" htmlEscape="true"/></span>
		</div>
		<input type="button" value="Cancelar" onclick="cerrarDlgClabe()" class="buttonDlg"/>
		<input type="button" value="Enviar" onclick="setClabe()" class="buttonDlg"/>
	</div>
</div>

src/SolSSIApp/WebContent/WEB-INF/jsp/autorizacion/result.jsp
<%@ page contentType="text/html" isELIgnored="false"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt"%>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form"%>
<%@ taglib prefix="s" uri="http://www.springframework.org/tags"%>


<script>
		
		function salir(){
			document.forms["form"].action = "<s:url value='/autorizacion'/>";
			document.forms["form"].submit();
		}
		
</script>

<s:url value="/inicio/busqueda" var="urlConsulta"/>
<br/>
<div align="center" class="ui-widget-content ui-corner-all" style="width: 75%">
		<div class="moduleTitle">
			<c:choose>
				<c:when test="${empty error and autorizado eq 'true'}">
					<div><img src="<s:url value='/resources/images/sucess.png'/>" width="60px" height="60px"></div>
					<span><s:message code="auth.result.satisfactorio" htmlEscape="true" arguments="${folio}"/></span>
				</c:when>
				<c:when test="${empty error and rechazado eq 'true'}">
					<div><img src="<s:url value='/resources/images/rechazar32.png'/>" width="40px" height="40px"></div>
						<span><s:message code="auth.result.nosatisfactorio" htmlEscape="true" arguments="${folio}"/></span>
					</c:when>
				<c:otherwise>
					<div><img src="<s:url value='/resources/images/warning_blue.png'/>"></div>
					<span>Error al ejecutar la operaci&oacute;n</span>
				</c:otherwise>
			</c:choose>
		</div>
			<div id="containerInicio" align="center">
				<br/>
			    <form name="form" method="post">
					<table style="width: 100%" align="center">
					    <c:if test="${not empty error}">
						<tr>
							<td align="center">
								<span class="leyenda">
								    <c:out value="${error}"/>
								</span>
							</td>
						</tr>
						</c:if>
						<tr>
							<td align="center">
								<button type="button" class="btnEnviar" onclick="salir()"><span><em>Salir</em></span></button>
							</td>
						</tr>
						<tr><td>&nbsp;</td></tr>
					</table>
				</form>
			</div>	
</div>