src/SolSSIApp/src/mx/com/metlife/solssi/esquemas/domain/AtributoEsquema.java
package mx.com.metlife.solssi.esquemas.domain;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.springframework.util.StringUtils;

@Entity
@Table(name="TR_ESQUEMAS_ATRIBUTOS")
public class AtributoEsquema implements Comparable<AtributoEsquema>, Serializable{
	
	/**
	 * 
	 */
	private static final long serialVersionUID = 8481907959692928496L;

	private AtributoEsquemaPK pk = new AtributoEsquemaPK();
	
	private String valor;

	
	@Transient
	public Atributo getAtributo(){
		return pk.getAtributo();
	}
	
	@Transient
	public String getNombre(){
		return pk.getAtributo().getNombre();
	}
	
	@Transient
	public Esquema getEsquema(){
		return pk.getEsquema();
	}
	
	public void setEsquema(Esquema esquema){
		this.getPk().setEsquema(esquema);
	}
	
	public void setAtributo(Atributo atributo){
		this.getPk().setAtributo(atributo);
	}
	
	/**
	 * @return the getValor
	 */
	@Column(name = "VALOR")
	public String getValor() {
		return StringUtils.trimWhitespace(valor);
	}

	/**
	 * @param getValor the getValor to set
	 */
	public void setValor(String valor) {
		this.valor = valor;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((pk == null) ? 0 : pk.hashCode());
		return result;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (!(obj instanceof AtributoEsquema))
			return false;
		AtributoEsquema other = (AtributoEsquema) obj;
		if (pk == null) {
			if (other.pk != null)
				return false;
		} else if (!pk.equals(other.pk))
			return false;
		return true;
	}

	/**
	 * @return the pk
	 */
	@EmbeddedId
	public AtributoEsquemaPK getPk() {
		return pk;
	}

	/**
	 * @param pk the pk to set
	 */
	public void setPk(AtributoEsquemaPK pk) {
		this.pk = pk;
	}
	
	public int compareTo(AtributoEsquema o) {
		if(this.getPk() == null || o.getPk() == null){
			return 0;
		}
		
		if(this.getPk().getAtributo() == null || o.getPk().getAtributo() == null){
			return 0;
		}
		
		if(this.getPk().getAtributo().getOrden() == null || o.getPk().getAtributo().getOrden() == null){
			return 0;
		}
		
		return this.getPk().getAtributo().getOrden().compareTo(o.getPk().getAtributo().getOrden());
	}

	
}

src/SolSSIApp/src/mx/com/metlife/solssi/esquemas/domain/OficioFilterEsquema.java
package mx.com.metlife.solssi.esquemas.domain;

import mx.com.metlife.solssi.oficio.domain.OficioFilter;

public class OficioFilterEsquema extends OficioFilter {
	
}

src/SolSSIApp/src/mx/com/metlife/solssi/oficio/domain/ControlCode.java
package mx.com.metlife.solssi.oficio.domain;

public class ControlCode {
	
	private int totalSolicitudes;
	
	private int totalPorcentajes;
	
	private int totalRechazadas;
	
	private int totalAceptadas;
	
	private long sumaClabes;
	
	private long sumaFolios;
	
	/**
	 * @return el totalSolicitudes
	 */
	public int getTotalSolicitudes() {
		return totalSolicitudes;
	}

	/**
	 * @param totalSolicitudes el totalSolicitudes a establecer
	 */
	public void setTotalSolicitudes(int totalSolicitudes) {
		this.totalSolicitudes = totalSolicitudes;
	}

	/**
	 * @return el totalPorcentajes
	 */
	public int getTotalPorcentajes() {
		return totalPorcentajes;
	}

	/**
	 * @param totalPorcentajes el totalPorcentajes a establecer
	 */
	public void setTotalPorcentajes(int totalPorcentajes) {
		this.totalPorcentajes = totalPorcentajes;
	}

	/**
	 * @return el sumaFolios
	 */
	public long getSumaFolios() {
		return sumaFolios;
	}

	/**
	 * @param sumaFolios el sumaFolios a establecer
	 */
	public void setSumaFolios(long sumaFolios) {
		this.sumaFolios = sumaFolios;
	}

	
	
	/**
	 * @return el totalRechazadas
	 */
	public int getTotalRechazadas() {
		return totalRechazadas;
	}

	/**
	 * @param totalRechazadas el totalRechazadas a establecer
	 */
	public void setTotalRechazadas(int totalRechazadas) {
		this.totalRechazadas = totalRechazadas;
	}
	
	

	public int getTotalAceptadas() {
		return totalAceptadas;
	}

	public void setTotalAceptadas(int totalAceptadas) {
		this.totalAceptadas = totalAceptadas;
	}
	
	

	/**
	 * @return el sumaClabes
	 */
	public long getSumaClabes() {
		return sumaClabes;
	}

	/**
	 * @param sumaClabes el sumaClabes a establecer
	 */
	public void setSumaClabes(long sumaClabes) {
		this.sumaClabes = sumaClabes;
	}

	/**
	 * 
	 * @return
	 */
	public String getControlCode() {
		StringBuilder str = new StringBuilder();
		str.append(this.totalSolicitudes);
		str.append("-");
		str.append(this.totalAceptadas);
		str.append("-");
		str.append(this.totalPorcentajes);
		str.append("-");
		str.append(this.sumaFolios);
		str.append("-");
		str.append(this.sumaClabes);
		return  str.toString(); 
	}
	
	public String getControlCodeEsquemas() {
		
		StringBuilder str = new StringBuilder();
		str.append(this.totalSolicitudes);
		str.append("-");
		str.append(this.totalAceptadas);
		str.append("-");
		str.append(this.sumaFolios);
		str.append("-");
		str.append(this.sumaClabes);
		return  str.toString(); 
	}
	
	
	/**
	 * 
	 * @return
	 */
	public String getControlCodeSave() {

		StringBuilder str = new StringBuilder();
		str.append(this.totalAceptadas);
		str.append("-");
		str.append(this.totalPorcentajes);
		str.append("-");
		str.append(this.sumaFolios);
		str.append("-");
		str.append(this.sumaClabes);
		
		if(str.length() > 50){
			return  str.substring(0, 50);	
		}
		
		return str.toString(); 
	}
	
	

}

src/SolSSIApp/src/mx/com/metlife/solssi/esquemas/mvc/AutorizacionEsquemasController.java
package mx.com.metlife.solssi.esquemas.mvc;

import java.util.List;

import javax.servlet.http.HttpSession;
import javax.validation.Valid;

import mx.com.metlife.solssi.esquemas.domain.ConsultaFilterEsquema;
import mx.com.metlife.solssi.esquemas.domain.SolicitudEsquema;
import mx.com.metlife.solssi.esquemas.service.SolicitudEsquemaService;
import mx.com.metlife.solssi.exception.ApplicationException;
import mx.com.metlife.solssi.inicio.service.GruposCapturaService;
import mx.com.metlife.solssi.usuario.domain.UserPrincipal;
import mx.com.metlife.solssi.usuario.domain.Usuario;
import mx.com.metlife.solssi.util.AppConstants;
import mx.com.metlife.solssi.util.BrowserUtils;

import org.apache.commons.lang.StringUtils;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.security.core.Authentication;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;

@Controller
@RequestMapping("esquemas/autorizacion")
public class AutorizacionEsquemasController {
	
	@Autowired
	private SolicitudEsquemaService solicitudService;
	
	@Autowired
	private GruposCapturaService groupService;
	
	@RequestMapping(method=RequestMethod.POST)
	public String showConsulta(Model model, HttpSession session){
		
		session.removeAttribute("solicitud");
		
		model.addAttribute(new ConsultaFilterEsquema());
		return "esquemas/autorizacion";
	}
	
	
	@RequestMapping(value = "consulta", method=RequestMethod.POST)
	public String executeConsulta(@Valid ConsultaFilterEsquema filtro, BindingResult errors, Model model, Authentication auth){
		
		Usuario usuario = ((UserPrincipal)auth.getPrincipal()).getUsuario();
		
		model.addAttribute(filtro);
		
		if(usuario.getDependencia() == null || usuario.getDependencia() <= 0){
			errors.reject("NotEmpty.consultaFilter.dependencia");
		}
		
		if(filtro.isEmpty()){
			errors.reject("NotEmpty.consultaFilter.object");
			return "esquemas/autorizacion";
		}
		
		if(errors.hasErrors()){
			return "esquemas/autorizacion";	
		}
		
		filtro.setDependencia(usuario.getDependencia());
		filtro.setEstatus(AppConstants.ESTATUS_CAPTURA);
		List<SolicitudEsquema> list = solicitudService.get(filtro);
		
		if(list == null || list.isEmpty()){
			if(filtro.getNumFolio()!=null && filtro.getNumFolio()>0){
				errors.reject("NotEmpty.auth.result.folio");	
			}else{
				errors.reject("NotEmpty.auth.result.rfc_cuenta");
			}
		}
		
		model.addAttribute("solicitudes", list);
		
		BrowserUtils.enableHistoryBack(model);
		
		return "esquemas/autorizacion";
	}
	
	@RequestMapping(value = "desplegar", method=RequestMethod.POST)
	public String showSolicitud(@RequestParam("numFolio") Integer folio, HttpSession session, Model model){
		
		SolicitudEsquema solicitud = solicitudService.get(folio);
		session.setAttribute("solicitud", solicitud);
		model.addAttribute("auth", true);
		
		return "esquemas/autorizacion/solicitud";
	}
	
	
	
	@RequestMapping(value = "execute/autorizacion", method=RequestMethod.POST)
	public String executeAutorizacion(@RequestParam(value = "nivelPuesto", required = false) String nivelPuesto, Model model, HttpSession session, Authentication auth){
		
		Usuario usuario = ((UserPrincipal)auth.getPrincipal()).getUsuario();
		
		SolicitudEsquema solicitud = (SolicitudEsquema) session.getAttribute("solicitud");
		
		try {
			
			groupService.checkFechaMaxAutorizacionEsquemas();
			
			if(StringUtils.isNotEmpty(nivelPuesto)){
				solicitudService.updateNivelPuesto(solicitud.getNumFolio(), nivelPuesto);	
			}
			
			solicitudService.updateEstatusAutorizacion(solicitud, AppConstants.ESTATUS_ACEPTADO, usuario.getClave());
			
			model.addAttribute("autorizado", "true");
			
		} catch (ApplicationException e) {
			model.addAttribute("error", e.getMessage());
		}
		
		model.addAttribute("folio", solicitud.getUserFolio());
		
		session.removeAttribute("solicitud");
		
		return "esquemas/autorizacion/result";
	}
	
	
	
	
	@RequestMapping(value = "execute/rechazo" , method=RequestMethod.POST)
	public String executeRechazo(Model model, HttpSession session, Authentication auth){
		try {
			
			groupService.checkFechaMaxAutorizacionEsquemas();
			
			Usuario usuario = ((UserPrincipal)auth.getPrincipal()).getUsuario();
			
			SolicitudEsquema solicitud = (SolicitudEsquema) session.getAttribute("solicitud");
			model.addAttribute("folio", solicitud.getUserFolio());
			
			groupService.checkFechaMaxAutorizacionEsquemas();
			
			solicitudService.updateEstatusAutorizacion(solicitud, AppConstants.ESTATUS_RECHAZADO, usuario.getClave());
			model.addAttribute("rechazado", "true");
			
		} catch (ApplicationException e) {
			model.addAttribute("error", e.getMessage());
		}
		
		session.removeAttribute("solicitud");
		
		return "esquemas/autorizacion/result";
	}



}

src/SolSSIApp/src/mx/com/metlife/solssi/esquemas/mvc/ConsultaSolicitudEsquemaController.java
package mx.com.metlife.solssi.esquemas.mvc;

import java.util.List;

import javax.validation.Valid;

import mx.com.metlife.solssi.esquemas.domain.ConsultaFilterEsquema;
import mx.com.metlife.solssi.esquemas.domain.SolicitudEsquema;
import mx.com.metlife.solssi.esquemas.service.SolicitudEsquemaService;
import mx.com.metlife.solssi.usuario.domain.UserPrincipal;
import mx.com.metlife.solssi.usuario.domain.Usuario;
import mx.com.metlife.solssi.util.BrowserUtils;

import org.apache.commons.lang.StringUtils;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.security.core.Authentication;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;

@Controller
@RequestMapping("esquemas/consulta")
public class ConsultaSolicitudEsquemaController {
	
	@Autowired
	private SolicitudEsquemaService solicitudService;
	
	@RequestMapping(method=RequestMethod.POST)
	public String showConsulta(Model model){
		model.addAttribute(new ConsultaFilterEsquema());
		return "esquemas/consulta";
	}
	
	
	@RequestMapping(value = "execute", method=RequestMethod.POST)
	public String executeConsulta(@Valid ConsultaFilterEsquema filtro, BindingResult errors, Model model, Authentication auth){
		
		Usuario usuario = ((UserPrincipal)auth.getPrincipal()).getUsuario();
		
		model.addAttribute(filtro);
		
		if(filtro.isEmpty()){
			errors.reject("NotEmpty.consultaFilter.object");
			return "esquemas/consulta";
		}
		
		if(errors.hasErrors()){
			return "esquemas/consulta";	
		}
		
		filtro.setDependencia(usuario.getDependencia());
		List<SolicitudEsquema> list = solicitudService.get(filtro);
		
		model.addAttribute("solicitudes", list);
		
		this.checkErroresResult(list, filtro, usuario, errors);
		
		BrowserUtils.enableHistoryBack(model);
		
		return "esquemas/consulta";
	}
	
	@RequestMapping(value = "view", method=RequestMethod.POST)
	public String showSolicitud(@RequestParam("numFolio") Integer folio, Model model){
		
		SolicitudEsquema solicitud = solicitudService.get(folio);
		model.addAttribute("solicitud", solicitud);
		model.addAttribute("urlRegresar", "/consulta");
		
		return "esquemas/consulta/solicitud";
	}
	
	/**
	 * revisa si existen errores en el resultado de la consulta
	 * @param list
	 * @param filtro
	 * @param usuario
	 * @param errors
	 */
	private void checkErroresResult(List<SolicitudEsquema> list, ConsultaFilterEsquema filtro, Usuario usuario, BindingResult errors){
	
		if(list == null || list.isEmpty()){
			if(usuario.getDependencia() != null && usuario.getDependencia() > 0){
				if(filtro.getNumFolio()!=null && filtro.getNumFolio()>0){
					errors.reject("NotEmpty.consultaFilter.dependencia.folio");	
				}else{
					if(StringUtils.isNotEmpty(filtro.getRfc())){
						errors.reject("NotEmpty.consultaFilter.dependencia.rfc");
					}else{
						if(StringUtils.isNotEmpty(filtro.getCuenta())){
							errors.reject("NotEmpty.consultaFilter.dependencia.cuenta");	
						}
					}
				}
				
			}else{
				if(filtro.getNumFolio()!=null && filtro.getNumFolio()>0){
					errors.reject("NotEmpty.consultaFilter.callcenter.folio");	
				}else{
					if(StringUtils.isNotEmpty(filtro.getRfc())){
						errors.reject("NotEmpty.consultaFilter.callcenter.rfc");
					}else{
						if(StringUtils.isNotEmpty(filtro.getCuenta())){
							errors.reject("NotEmpty.consultaFilter.callcenter.cuenta");	
						}
					}
				}
			}
		}
	}


}

src/SolSSIApp/src/mx/com/metlife/solssi/esquemas/mvc/SolicitudEsquemasController.java
package mx.com.metlife.solssi.esquemas.mvc;

import javax.servlet.http.HttpSession;
import javax.validation.Valid;

import mx.com.metlife.solssi.cliente.domain.Cliente;
import mx.com.metlife.solssi.esquemas.domain.SolicitudEsquema;
import mx.com.metlife.solssi.esquemas.service.SolicitudEsquemaService;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.SessionAttributes;

@Controller
@RequestMapping("esquemas/solicitud")
@SessionAttributes("solicitudEsquema")
public class SolicitudEsquemasController {
	
	@Autowired
	private SolicitudEsquemasValidator validator;
	
	@Autowired
	private SolicitudEsquemaService solicitudService;
	
	
	@RequestMapping("validate")
	public String showSeleccion(@Valid SolicitudEsquema solicitud, BindingResult errors, Model model, HttpSession session){

		if(!validator.validaCaptcha(solicitud, session)){
			model.addAttribute("validCaptcha", "false");
			model.addAttribute(solicitud);
			return "esquemas/solicitud";
		}
		
		validator.validate(solicitud, errors);
		
		if(errors.hasErrors()){
			model.addAttribute(solicitud);
			return "esquemas/solicitud";	
		}
		
		return "esquemas/seleccion";
	}
	
	
	@RequestMapping("regresar")
	public String showSeleccion(){
		return "esquemas/solicitud";
	}

	
	@RequestMapping(value = "save", method = RequestMethod.POST)
	public String save(Model model, HttpSession session){

		Boolean saved = (Boolean) session.getAttribute("SolicitudSaved");
		
		if(saved != null && saved){
			return "esquemas/solicitud/result";
		}
		
		Cliente cliente = (Cliente) session.getAttribute("cliente");
		SolicitudEsquema solicitud = (SolicitudEsquema) session.getAttribute("solicitudEsquema");
		
		solicitud.setCuenta(cliente.getCuenta());
		solicitud.setRfc(cliente.getRfc());
		solicitud.setHomoclave(cliente.getHomoclave());
		solicitud.setCentroTrabajo(cliente.getClaveDependencia().shortValue());
		solicitud.setNivelPuesto(cliente.getNivelPuesto());
		
		solicitudService.save(solicitud);
		
		session.setAttribute("SolicitudSaved", true);
		
		return "esquemas/solicitud/result";
	
	}

}

src/SolSSIApp/WebContent/WEB-INF/jsp/esquemas/oficio/oficio_detalle.jsp
<%@ page contentType="text/html" isELIgnored="false"%>

<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt"%>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form"%>
<%@ taglib prefix="s" uri="http://www.springframework.org/tags"%>
<%@ taglib prefix="sec"	uri="http://www.springframework.org/security/tags"%>

<script>
	

	function showSolicitud(numFolio) {
		document.forms["solicitud"].numFolio.value = numFolio;
		document.forms["solicitud"].submit();
	}
	
</script>

   <div style="width: 100%" align="center">
		
		<div class="moduleTitle"><span>Detalle de Oficio <c:out value="${oficio.numOficio}"/></span></div>
		
		<c:if test="${not empty solicitudes}">
				<br/>
				<div align="center" style="width:80%" class="ui-widget-content ui-corner-all">
				<table class="display" align="center">
					<tr class="ui-state-default">
						<td align="center">
						    Num Oficio
						</td>
						<td align="center">
						    Fecha<br/> Generaci&oacute;n
						</td>
						<td align="center">
						    Fecha<br/> Autorizaci&oacute;n
						</td>
						<td align="center">
						    Fecha<br/> Envio
						</td>
						<td align="center">
						    Total<br/> Documentos
						</td>
						<td align="center">
						    Total<br/> Satisfactorios
						</td>
						<td align="center">
						    Cifra<br/> de Control
						</td>
					</tr>
					<tr>
						<td align="center">
						    <c:out value="${oficio.numOficio}"/>
						</td>
						<td align="center">
						    <fmt:formatDate value="${oficio.fechaGeneracion}" pattern="dd-MM-yyyy HH:mm"/>
						</td>
						<td align="center">
						    <fmt:formatDate value="${oficio.fechaAceptacion}" pattern="dd-MM-yyyy HH:mm"/>
						</td>
						<td align="center">
						    <fmt:formatDate value="${oficio.fechaEnvio}" pattern="dd-MM-yyyy HH:mm"/>
						</td>
						<td align="center">
						    <c:out value="${control.totalSolicitudes}"/>
						</td>
						<td align="center">
						    <c:out value="${control.totalAceptadas}"/>
						</td>
						<td align="center">
						    <c:out value="${control.controlCodeEsquemas}"/>
						</td>
					</tr>
				</table>
				</div>
				<br/>
				<div id="tablaTramites" align="center" class="ui-widget-content ui-corner-all" style="width: 80%">
					<table  class="display" style="width: 100%;padding-top: 30px" align="center">
						<thead class="ui-widget-header">
							<tr>
								<th><s:message code="table.header.solicitud.num" htmlEscape="true"/></th>
								<th><s:message code="table.header.solicitud.folio" htmlEscape="true"/></th>
								<th><s:message code="table.header.solicitud.cuenta" htmlEscape="true"/></th>
								<th><s:message code="table.header.solicitud.rfc" htmlEscape="true"/></th>
								<th><s:message code="table.header.solicitud.estatus" htmlEscape="true"/></th>
								<th><s:message code="table.header.esquema.fechaSolicitud" htmlEscape="true"/></th>
								<th><s:message code="table.header.esquema.desplegar" htmlEscape="true"/></th>
							</tr>
						</thead>
						<tbody>
						</tbody>
			
						<c:forEach items="${solicitudes}" var="sol" varStatus="st">
							
							<c:choose>
						    	<c:when test="${st.count % 2 == 1}">
						    		<c:set var="css" value="odd"/>
						    	</c:when>
						    	<c:otherwise>
						    		<c:set var="css" value="even"/>
						    	</c:otherwise>
						    </c:choose>
							<c:set var="estatus"><c:out value="${sol.estatus}"/></c:set>
							
							<tr class="${css}">
								<td><c:out value="${st.count}"/></td>
								<td><c:out value="${sol.userFolio}"/></td>
								<td><c:out value="${sol.cuenta}"/></td>
								<td><c:out value="${sol.rfc}"/></td>
								<td><c:out value="${CATALOGO.ESTATUS_TRAMITE[estatus].valorCampo2}"/></td>
								<td><fmt:formatDate  value="${sol.fechaCaptura}" pattern="dd-MM-yyyy HH:mm:ss"/></td>
								<td><a href="javascript:showSolicitud(${sol.numFolio})" style="color: blue;text-decoration: underline;">
									<img src="<s:url value='/resources/images/edit-find32.png'/>" alt="Desplegar" height="17px" width="17px"/></a>
								</td>
							</tr>
						</c:forEach>
					</table>
				</div>
				<br/><br/>
		</c:if>
		<button type="button" class="btnEnviar" onclick="history.back()"><span><em>Regresar</em></span></button>
	</div>	

	
	<form name="solicitud" action="<s:url value='/esquemas/consulta/view'/>" method="post">
		<input type="hidden" name="numFolio"/>
	</form>

src/SolSSIApp/WebContent/WEB-INF/jsp/esquemas/oficio/oficio_existente.jsp
<%@ page contentType="text/html" isELIgnored="false"%>

<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt"%>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form"%>
<%@ taglib prefix="s" uri="http://www.springframework.org/tags"%>


<script>

	function imprimirOficio() {
		openWindowCenter("", "oficiopdf", 1000, 600);
		document.forms["print"].submit();
	}
	
	function showDetalleOficio(numOficio) {
		document.forms["detalle"].oficio.value = numOficio;
		submitForm(document.forms["detalle"]);
	}
	
	
</script>

<style>

	#filtro li {
		float: left;
		margin: 0px 20px 0px 0px;
		list-style-type: none;
		height: 50px
	}

</style>
<c:set var="oficio" value="${oficioEsquema}"/>
<div class="moduleTitle"><span><s:message code="module.title.oficio.generar" htmlEscape="true"/></span></div>

		<div>
			<span class="error"><s:message code="oficio.alredy.generated.dependencia"/></span>
		</div>
		
		<br/>
		
		<div id="tablaTramites" align="center" class="ui-widget-content ui-corner-all" style="width: 80%">
			<form name="oficios" method="post">
				<table  class="display" style="width: 100%;padding-top: 30px" align="center">
					<thead class="ui-widget-header">
						<tr>
							<th>Oficio</th>
							<th>Dependencia</th>
							<th>Fecha Generaci&oacute;n</th>
							<th>Detalle</th>
							<th>Estatus</th>
							<th>Reimprimir</th>
						</tr>
					</thead>
					<tbody>
					</tbody>
		
						<c:set var="cveDependencia">${oficio.dependencia}</c:set>
						<c:choose>
					    	<c:when test="${st.count % 2 == 1}">
					    		<c:set var="css" value="odd"/>
					    	</c:when>
					    	<c:otherwise>
					    		<c:set var="css" value="even"/>
					    	</c:otherwise>
					    </c:choose>
		
						<tr class="${css}">
							<td><c:out value="${oficio.numOficio}"/></td>
							<td><c:out value="${CATALOGO.DEPENDENCIAS[cveDependencia].descripcion}"/></td>
							<td><fmt:formatDate value="${oficio.fechaGeneracion}" pattern="dd-MM-yyyy HH:mm:ss"/></td>
							
							
							<td><a href="javascript:showDetalleOficio(<c:out value='${oficio.numOficio}'/>)" style="color: blue;text-decoration: underline;">
								Detalle</a></td>
							
							<td>
								<c:choose>
									<c:when test="${oficio.estatus eq 1}">
										Generado
									</c:when>
									<c:when test="${oficio.estatus eq 3}">
										Enviado
									</c:when>
									<c:when test="${oficio.estatus eq 2}">
										Aceptado
									</c:when>
								</c:choose>
							</td>
							<td>
								<a href="javascript:imprimirOficio()">Imprimir</a>
							</td>
						</tr>
						
				</table>
			</form>	
		</div>
		

		<form name="detalle" action="<s:url value='/esquemas/oficio/detalle'/>" method="post">
			<input name="oficio" type="hidden"/>
		</form>
		
		<form name="print" action="<s:url value='/esquemas/oficio/reimpresion'/>"
		method="post" target="oficiopdf"></form>