src/SolSSIApp/src/mx/com/metlife/solssi/esquemas/domain/AtributoEsquema.java
package mx.com.metlife.solssi.esquemas.domain;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.springframework.util.StringUtils;

@Entity
@Table(name="TR_ESQUEMAS_ATRIBUTOS")
public class AtributoEsquema implements Comparable<AtributoEsquema>, Serializable{
	
	/**
	 * 
	 */
	private static final long serialVersionUID = 8481907959692928496L;

	private AtributoEsquemaPK pk = new AtributoEsquemaPK();
	
	private String valor;

	
	@Transient
	public Atributo getAtributo(){
		return pk.getAtributo();
	}
	
	@Transient
	public String getNombre(){
		return pk.getAtributo().getNombre();
	}
	
	@Transient
	public Esquema getEsquema(){
		return pk.getEsquema();
	}
	
	public void setEsquema(Esquema esquema){
		this.getPk().setEsquema(esquema);
	}
	
	public void setAtributo(Atributo atributo){
		this.getPk().setAtributo(atributo);
	}
	
	/**
	 * @return the getValor
	 */
	@Column(name = "VALOR")
	public String getValor() {
		return StringUtils.trimWhitespace(valor);
	}

	/**
	 * @param getValor the getValor to set
	 */
	public void setValor(String valor) {
		this.valor = valor;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((pk == null) ? 0 : pk.hashCode());
		return result;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (!(obj instanceof AtributoEsquema))
			return false;
		AtributoEsquema other = (AtributoEsquema) obj;
		if (pk == null) {
			if (other.pk != null)
				return false;
		} else if (!pk.equals(other.pk))
			return false;
		return true;
	}

	/**
	 * @return the pk
	 */
	@EmbeddedId
	public AtributoEsquemaPK getPk() {
		return pk;
	}

	/**
	 * @param pk the pk to set
	 */
	public void setPk(AtributoEsquemaPK pk) {
		this.pk = pk;
	}
	
	public int compareTo(AtributoEsquema o) {
		if(this.getPk() == null || o.getPk() == null){
			return 0;
		}
		
		if(this.getPk().getAtributo() == null || o.getPk().getAtributo() == null){
			return 0;
		}
		
		if(this.getPk().getAtributo().getOrden() == null || o.getPk().getAtributo().getOrden() == null){
			return 0;
		}
		
		return this.getPk().getAtributo().getOrden().compareTo(o.getPk().getAtributo().getOrden());
	}

	
}

src/SolSSIApp/src/mx/com/metlife/solssi/esquemas/domain/OficioFilterEsquema.java
package mx.com.metlife.solssi.esquemas.domain;

import mx.com.metlife.solssi.oficio.domain.OficioFilter;

public class OficioFilterEsquema extends OficioFilter {
	
}

src/SolSSIApp/src/mx/com/metlife/solssi/consulta/mvc/ConsultaController.java
package mx.com.metlife.solssi.consulta.mvc;

import java.util.List;

import javax.servlet.http.HttpSession;
import javax.validation.Valid;

import mx.com.metlife.solssi.consulta.domain.ConsultaFilter;
import mx.com.metlife.solssi.consulta.domain.ReporteTotales;
import mx.com.metlife.solssi.esquemas.service.SolicitudEsquemaService;
import mx.com.metlife.solssi.solicitud.domain.Solicitud;
import mx.com.metlife.solssi.solicitud.service.SolicitudService;
import mx.com.metlife.solssi.usuario.domain.UserPrincipal;
import mx.com.metlife.solssi.usuario.domain.Usuario;
import mx.com.metlife.solssi.util.BrowserUtils;

import org.apache.commons.lang.StringUtils;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.security.core.Authentication;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;




@Controller
@RequestMapping("consulta")
public class ConsultaController {
	
	@Autowired
	private SolicitudService solicitudService;
	
	@Autowired
	private SolicitudEsquemaService solicitudEsquemaService;
	
	@RequestMapping(method=RequestMethod.POST)
	public String showConsulta(Model model){
		model.addAttribute(new ConsultaFilter());
		return "consulta";
	}
	
	
	@RequestMapping(value = "execute", method=RequestMethod.POST)
	public String executeConsulta(@Valid ConsultaFilter filtro, BindingResult errors, Model model, Authentication auth){
		
		Usuario usuario = ((UserPrincipal)auth.getPrincipal()).getUsuario();
		
		model.addAttribute(filtro);
		
		if(filtro.isEmpty()){
			errors.reject("NotEmpty.consultaFilter.object");
			return "consulta";
		}
		
		if(errors.hasErrors()){
			return "consulta";	
		}
		
		filtro.setDependencia(usuario.getDependencia());
		List<Solicitud> list = solicitudService.get(filtro, true);
		
		model.addAttribute("solicitudes", list);
		
		this.checkErroresResult(list, filtro, usuario, errors);
		
		BrowserUtils.enableHistoryBack(model);
		
		return "consulta";
	}
	
	@RequestMapping(value = "view", method=RequestMethod.POST)
	public String showSolicitud(@RequestParam("numFolio") Integer folio, Model model){
		
		Solicitud solicitud = solicitudService.get(folio);
		model.addAttribute("solicitud", solicitud);
		model.addAttribute("urlRegresar", "/consulta");
		
		return "consulta/solicitud";
	}
	
	@RequestMapping(value = "dependientes" , method=RequestMethod.POST)
	public String showDependientes(@RequestParam("folio") Integer folio, Model model, HttpSession session){
		
		Solicitud solicitud = solicitudService.get(folio);
		session.setAttribute("solicitud", solicitud);
		
		return "consulta/dependientes";
	}
	
	@RequestMapping("dependientes/regresar")
	public String backDependientes(){
		return "consulta/dependientes";
	}
	
	
	@RequestMapping(value = "info/dependiente", method=RequestMethod.POST)
	public String showDependienteInfo(@RequestParam("numero") Short numero, Model model, HttpSession session){
		
		Solicitud solicitud = (Solicitud) session.getAttribute("solicitud");
		model.addAttribute(solicitud.getDependiente(numero));
		
		return "consulta/info/dependiente";
	}
	
	@RequestMapping(value = "totales", method=RequestMethod.POST)
	public String showTotalesPage(Model model){
		model.addAttribute(new ConsultaFilter());
		return "consulta/totales";
	}
	
	@RequestMapping(value = "totales/execute", method=RequestMethod.POST)
	public String executeTotalesPage(ConsultaFilter filter, Model model){
		ReporteTotales reporte = solicitudService.getTotales(filter.getDependencia());
		ReporteTotales reporteEsquemas = solicitudEsquemaService.getTotales(filter.getDependencia());
		model.addAttribute("reporte", reporte);
		model.addAttribute("reporteEsquemas", reporteEsquemas);
		model.addAttribute(filter);
		return "consulta/totales";
	}
	
	
	/**
	 * revisa si existen errores en el resultado de la consulta
	 * @param list
	 * @param filtro
	 * @param usuario
	 * @param errors
	 */
	private void checkErroresResult(List<Solicitud> list, ConsultaFilter filtro, Usuario usuario, BindingResult errors){
	
		if(list == null || list.isEmpty()){
			if(usuario.getDependencia() != null && usuario.getDependencia() > 0){
				if(filtro.getNumFolio()!=null && filtro.getNumFolio()>0){
					errors.reject("NotEmpty.consultaFilter.dependencia.folio");	
				}else{
					if(StringUtils.isNotEmpty(filtro.getRfc())){
						errors.reject("NotEmpty.consultaFilter.dependencia.rfc");
					}else{
						if(StringUtils.isNotEmpty(filtro.getCuenta())){
							errors.reject("NotEmpty.consultaFilter.dependencia.cuenta");	
						}
					}
				}
				
			}else{
				if(filtro.getNumFolio()!=null && filtro.getNumFolio()>0){
					errors.reject("NotEmpty.consultaFilter.callcenter.folio");	
				}else{
					if(StringUtils.isNotEmpty(filtro.getRfc())){
						errors.reject("NotEmpty.consultaFilter.callcenter.rfc");
					}else{
						if(StringUtils.isNotEmpty(filtro.getCuenta())){
							errors.reject("NotEmpty.consultaFilter.callcenter.cuenta");	
						}
					}
				}
			}
		}
	}
	
}

src/SolSSIApp/src/mx/com/metlife/solssi/esquemas/mvc/AutorizacionEsquemasController.java
package mx.com.metlife.solssi.esquemas.mvc;

import java.util.List;

import javax.servlet.http.HttpSession;
import javax.validation.Valid;

import mx.com.metlife.solssi.esquemas.domain.ConsultaFilterEsquema;
import mx.com.metlife.solssi.esquemas.domain.SolicitudEsquema;
import mx.com.metlife.solssi.esquemas.service.SolicitudEsquemaService;
import mx.com.metlife.solssi.exception.ApplicationException;
import mx.com.metlife.solssi.inicio.service.GruposCapturaService;
import mx.com.metlife.solssi.usuario.domain.UserPrincipal;
import mx.com.metlife.solssi.usuario.domain.Usuario;
import mx.com.metlife.solssi.util.AppConstants;
import mx.com.metlife.solssi.util.BrowserUtils;

import org.apache.commons.lang.StringUtils;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.security.core.Authentication;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;

@Controller
@RequestMapping("esquemas/autorizacion")
public class AutorizacionEsquemasController {
	
	@Autowired
	private SolicitudEsquemaService solicitudService;
	
	@Autowired
	private GruposCapturaService groupService;
	
	@RequestMapping(method=RequestMethod.POST)
	public String showConsulta(Model model, HttpSession session){
		
		session.removeAttribute("solicitud");
		
		model.addAttribute(new ConsultaFilterEsquema());
		return "esquemas/autorizacion";
	}
	
	
	@RequestMapping(value = "consulta", method=RequestMethod.POST)
	public String executeConsulta(@Valid ConsultaFilterEsquema filtro, BindingResult errors, Model model, Authentication auth){
		
		Usuario usuario = ((UserPrincipal)auth.getPrincipal()).getUsuario();
		
		model.addAttribute(filtro);
		
		if(usuario.getDependencia() == null || usuario.getDependencia() <= 0){
			errors.reject("NotEmpty.consultaFilter.dependencia");
		}
		
		if(filtro.isEmpty()){
			errors.reject("NotEmpty.consultaFilter.object");
			return "esquemas/autorizacion";
		}
		
		if(errors.hasErrors()){
			return "esquemas/autorizacion";	
		}
		
		filtro.setDependencia(usuario.getDependencia());
		filtro.setEstatus(AppConstants.ESTATUS_CAPTURA);
		List<SolicitudEsquema> list = solicitudService.get(filtro);
		
		if(list == null || list.isEmpty()){
			if(filtro.getNumFolio()!=null && filtro.getNumFolio()>0){
				errors.reject("NotEmpty.auth.result.folio");	
			}else{
				errors.reject("NotEmpty.auth.result.rfc_cuenta");
			}
		}
		
		model.addAttribute("solicitudes", list);
		
		BrowserUtils.enableHistoryBack(model);
		
		return "esquemas/autorizacion";
	}
	
	@RequestMapping(value = "desplegar", method=RequestMethod.POST)
	public String showSolicitud(@RequestParam("numFolio") Integer folio, HttpSession session, Model model){
		
		SolicitudEsquema solicitud = solicitudService.get(folio);
		session.setAttribute("solicitud", solicitud);
		model.addAttribute("auth", true);
		
		return "esquemas/autorizacion/solicitud";
	}
	
	
	
	@RequestMapping(value = "execute/autorizacion", method=RequestMethod.POST)
	public String executeAutorizacion(@RequestParam(value = "nivelPuesto", required = false) String nivelPuesto, Model model, HttpSession session, Authentication auth){
		
		Usuario usuario = ((UserPrincipal)auth.getPrincipal()).getUsuario();
		
		SolicitudEsquema solicitud = (SolicitudEsquema) session.getAttribute("solicitud");
		
		try {
			
			groupService.checkFechaMaxAutorizacionEsquemas();
			
			if(StringUtils.isNotEmpty(nivelPuesto)){
				solicitudService.updateNivelPuesto(solicitud.getNumFolio(), nivelPuesto);	
			}
			
			solicitudService.updateEstatusAutorizacion(solicitud, AppConstants.ESTATUS_ACEPTADO, usuario.getClave());
			
			model.addAttribute("autorizado", "true");
			
		} catch (ApplicationException e) {
			model.addAttribute("error", e.getMessage());
		}
		
		model.addAttribute("folio", solicitud.getUserFolio());
		
		session.removeAttribute("solicitud");
		
		return "esquemas/autorizacion/result";
	}
	
	
	
	
	@RequestMapping(value = "execute/rechazo" , method=RequestMethod.POST)
	public String executeRechazo(Model model, HttpSession session, Authentication auth){
		try {
			
			groupService.checkFechaMaxAutorizacionEsquemas();
			
			Usuario usuario = ((UserPrincipal)auth.getPrincipal()).getUsuario();
			
			SolicitudEsquema solicitud = (SolicitudEsquema) session.getAttribute("solicitud");
			model.addAttribute("folio", solicitud.getUserFolio());
			
			groupService.checkFechaMaxAutorizacionEsquemas();
			
			solicitudService.updateEstatusAutorizacion(solicitud, AppConstants.ESTATUS_RECHAZADO, usuario.getClave());
			model.addAttribute("rechazado", "true");
			
		} catch (ApplicationException e) {
			model.addAttribute("error", e.getMessage());
		}
		
		session.removeAttribute("solicitud");
		
		return "esquemas/autorizacion/result";
	}



}

src/SolSSIApp/src/mx/com/metlife/solssi/esquemas/mvc/ConsultaSolicitudEsquemaController.java
package mx.com.metlife.solssi.esquemas.mvc;

import java.util.List;

import javax.validation.Valid;

import mx.com.metlife.solssi.esquemas.domain.ConsultaFilterEsquema;
import mx.com.metlife.solssi.esquemas.domain.SolicitudEsquema;
import mx.com.metlife.solssi.esquemas.service.SolicitudEsquemaService;
import mx.com.metlife.solssi.usuario.domain.UserPrincipal;
import mx.com.metlife.solssi.usuario.domain.Usuario;
import mx.com.metlife.solssi.util.BrowserUtils;

import org.apache.commons.lang.StringUtils;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.security.core.Authentication;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;

@Controller
@RequestMapping("esquemas/consulta")
public class ConsultaSolicitudEsquemaController {
	
	@Autowired
	private SolicitudEsquemaService solicitudService;
	
	@RequestMapping(method=RequestMethod.POST)
	public String showConsulta(Model model){
		model.addAttribute(new ConsultaFilterEsquema());
		return "esquemas/consulta";
	}
	
	
	@RequestMapping(value = "execute", method=RequestMethod.POST)
	public String executeConsulta(@Valid ConsultaFilterEsquema filtro, BindingResult errors, Model model, Authentication auth){
		
		Usuario usuario = ((UserPrincipal)auth.getPrincipal()).getUsuario();
		
		model.addAttribute(filtro);
		
		if(filtro.isEmpty()){
			errors.reject("NotEmpty.consultaFilter.object");
			return "esquemas/consulta";
		}
		
		if(errors.hasErrors()){
			return "esquemas/consulta";	
		}
		
		filtro.setDependencia(usuario.getDependencia());
		List<SolicitudEsquema> list = solicitudService.get(filtro);
		
		model.addAttribute("solicitudes", list);
		
		this.checkErroresResult(list, filtro, usuario, errors);
		
		BrowserUtils.enableHistoryBack(model);
		
		return "esquemas/consulta";
	}
	
	@RequestMapping(value = "view", method=RequestMethod.POST)
	public String showSolicitud(@RequestParam("numFolio") Integer folio, Model model){
		
		SolicitudEsquema solicitud = solicitudService.get(folio);
		model.addAttribute("solicitud", solicitud);
		model.addAttribute("urlRegresar", "/consulta");
		
		return "esquemas/consulta/solicitud";
	}
	
	/**
	 * revisa si existen errores en el resultado de la consulta
	 * @param list
	 * @param filtro
	 * @param usuario
	 * @param errors
	 */
	private void checkErroresResult(List<SolicitudEsquema> list, ConsultaFilterEsquema filtro, Usuario usuario, BindingResult errors){
	
		if(list == null || list.isEmpty()){
			if(usuario.getDependencia() != null && usuario.getDependencia() > 0){
				if(filtro.getNumFolio()!=null && filtro.getNumFolio()>0){
					errors.reject("NotEmpty.consultaFilter.dependencia.folio");	
				}else{
					if(StringUtils.isNotEmpty(filtro.getRfc())){
						errors.reject("NotEmpty.consultaFilter.dependencia.rfc");
					}else{
						if(StringUtils.isNotEmpty(filtro.getCuenta())){
							errors.reject("NotEmpty.consultaFilter.dependencia.cuenta");	
						}
					}
				}
				
			}else{
				if(filtro.getNumFolio()!=null && filtro.getNumFolio()>0){
					errors.reject("NotEmpty.consultaFilter.callcenter.folio");	
				}else{
					if(StringUtils.isNotEmpty(filtro.getRfc())){
						errors.reject("NotEmpty.consultaFilter.callcenter.rfc");
					}else{
						if(StringUtils.isNotEmpty(filtro.getCuenta())){
							errors.reject("NotEmpty.consultaFilter.callcenter.cuenta");	
						}
					}
				}
			}
		}
	}


}

src/SolSSIApp/WebContent/WEB-INF/jsp/esquemas/consulta/consulta_solicitud.jsp
<%@ page contentType="text/html" isELIgnored="false"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt"%>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form"%>
<%@ taglib prefix="s" uri="http://www.springframework.org/tags"%>
<%@ taglib prefix="sec"	uri="http://www.springframework.org/security/tags"%>

<s:url value="/esquemas/consulta" var="urlConsulta"/>

<script>
		 
		dojo.ready(function(){
			  
			
		});
		
		 
		 		 
		 function regresarConsulta(){
			 //document.forms["solicitud"].action = "<s:url value='/'/>${urlRegresar}";
			 //document.forms["solicitud"].target = "_top";
			 //document.forms["solicitud"].submit();
			 history.back();
		 }
		 
</script>

<div class="moduleTitle"><span><s:message code="module.title.solicitud.esquemas.consulta" htmlEscape="true"/></span></div>

<jsp:include page="datos_solicitud.jsp"/>

<br/>
	<div>
		<button type="button" class="btnEnviar" onclick="regresarConsulta()"><span><em>Regresar</em></span></button>
	</div>
<br/>

src/SolSSIApp/WebContent/WEB-INF/jsp/esquemas/consulta/datos_solicitud.jsp
<%@ page contentType="text/html" isELIgnored="false"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt"%>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form"%>
<%@ taglib prefix="s" uri="http://www.springframework.org/tags"%>
<%@ taglib prefix="sec"	uri="http://www.springframework.org/security/tags"%>

	<c:set var="estatus"><c:out value="${solicitud.estatus}"/></c:set>
	<div align="center">
		<table class="ui-widget-content ui-state-focus ui-corner-all seccion-solicitud">
				<tr>
					<td width="25%" align="right">
						Folio:						
					</td>
					<td width="25%" class="valueField">
						<c:out value="${solicitud.userFolio}"/>
					</td>
					<td width="25%" align="right">
						Estatus:						
					</td>
					<td class="valueField">
						<c:out value="${CATALOGO.ESTATUS_TRAMITE[estatus].valorCampo2}"/>
					</td>
				</tr>
				<tr>
					
				</tr>
				  
				<tr>
					<td width="25%" align="right">
						Esquema:						
					</td>
					<td class="valueField">
						<c:out value="${solicitud.esquema}"/>&nbsp;<c:out value="${esquemasInfo.esquemas[solicitud.esquema].nombre}"/>
					</td>
				</tr>
		</table>
	</div>


<div id="containerSolicitud" align="center" class="consultaSolicitud">      
      
	<form name="solicitud" id="solicitud" method="post" action="${urlProcesa}">
	     
		<br/>
		<div align="left" class="seccion">Datos Generales de Asegurado</div>
		<table class="ui-widget-content ui-corner-all seccion-solicitud">
			<tbody>
			
				<tr>
					<td class="tag">
					    <label for="estadoElaboracion">Estado de Elaboraci&oacute;n:</label>
					</td>
					<td class="valueField">
					      <c:set var="estadoElaboracion"><c:out value="${solicitud.estadoElaboracion}"/></c:set>
					      <c:out value="${CATALOGO.ESTADOS[estadoElaboracion].descripcion}"/>
	                </td>
	                <td class="tag">
					    <label for="estadoElaboracion">Ciudad de Elaboraci&oacute;n:</label>
					</td>
		             <td class="valueField">
		                  <c:out value="${solicitud.ciudadElaboracion}"/>
		             </td> 
				</tr>
				   
	            
	            <!-- Subseccion datos personales -->
		        <tr>
					<td colspan="2" align="left"><span class="subseccion">Datos Personales</span></td>
					<td colspan="2">&nbsp;</td>
				</tr>
	            
	            
	            <!-- Homoclave  y cuenta -->
				<tr>
					<td class="tag" ><label for="rfc">RFC - Homoclave:</label></td>
				    <td class="valueField" >
				        <c:out value="${solicitud.rfc}"/> <c:if test="${not empty solicitud.homoclave}">- <c:out value="${solicitud.homoclave}"/></c:if>
				    </td>
				    <td class="tag" ><label for="cuenta">N&uacute;mero de Cuenta:</label>
				    </td>
				    <td class="valueField">
				        <c:out value="${solicitud.cuenta}"/>
				    </td>    
				</tr>
				
		     <!-- Apellido paterno y materno -->  
		        <tr>
					<td class="tag" >
						<label for="apePaterno">Apellido Paterno:</label>
					</td>
					<td class="valueField" >
					    <c:out value="${solicitud.apePaterno}"/>
					</td>
					<td class="tag" >
					    <label for="apeMaterno">Apellido Materno:</label>
					</td>
					<td class="valueField" >
					    <c:out value="${solicitud.apeMaterno}"/>
				     </td>
				</tr>
		       
		       <!-- Nombre y fecha de nacimiento -->
		       <tr>
					<td class="tag" >
					    <label for="nombre">Nombre(s):</label>
					</td>
					<td class="valueField" >
						<c:out value="${solicitud.nombre}"/>
					</td>
				</tr>
		       
		       
		       <tr>
		       	    <td class="tag">
		       	        <label for="centroTrabajo">Centro de Trabajo:</label>
		       	    </td>
					<td class="valueField">
						<c:set var="centroTrabajo"><c:out value="${solicitud.centroTrabajo}"/></c:set>
					    <c:out value="${CATALOGO.DEPENDENCIAS[centroTrabajo].descripcion}"/>
				    </td>
	                <td class="tag">
		       	        <label for="nivelPuesto">Nivel de Puesto:</label>
	                </td>
	                <td class="valueField">
						<c:set var="nivelPuesto"><c:out value="${solicitud.nivelPuesto}"/></c:set>
					    <c:out value="${CATALOGO.NIVEL_PUESTO[nivelPuesto].descripcion}"/>
	                </td>
				</tr>
		       
		       
		       <!-- Tipo y numero de identificacion -->
		       <tr>
					<td class="tag" >
					     <label for="cveTipoIdentificacion">Identificaci&oacute;n Oficial:</label>
					</td>
				    <td class="valueField" >
						<c:set var="cveTipoIdentificacion"><c:out value="${solicitud.cveTipoIdentificacion}"/></c:set>
					    <c:out value="${CATALOGO.IDENTIFICACIONES[cveTipoIdentificacion].descripcion}"/>
					</td>
					<td class="tag" >
					    <label for="numeroIdentificacion">N&uacute;mero de Identificaci&oacute;n:</label>
					</td>
					<td class="valueField" >
					     <c:out value="${solicitud.numeroIdentificacion}"/>
					</td>
				</tr>
				
				<tr>
					<td colspan="2" align="left"><span class="subseccion">Correo Electr&oacute;nico</span></td>
					<td colspan="2">&nbsp;</td>
				</tr>
	
				<tr>
					<td class="tag" >
					       <label for="correoTrabajo">Correo Trabajo:</label>
					</td>
					<td class="valueField" >
						    <c:out value="${solicitud.correoTrabajo}"/>
					</td>
					<td class="tag" >
					      <label for="correoPersonal">Correo Personal:</label>
					</td>
					<td class="valueField" >
				           <c:out value="${solicitud.correoPersonal}"/>
					</td>
				</tr>
	
		       
		      </tbody>
	      </table>
	      <input type="hidden" name="nivelPuesto"/>
	</form>
</div>